services:
  ibis-app:
    build: .
    container_name: ibis-app

    env_file:
      - .env

    environment:
      - PYTHONUNBUFFERED=1

    volumes:
      - ./processed_orders.json:/app/processed_orders.json

    restart: unless-stopped