# odoo_client.py

import xmlrpc.client

from datetime import datetime, timedelta

from app.config import (
    ODOO_URL,
    ODOO_DB,
    ODOO_USERNAME,
    ODOO_PASSWORD
)


class OdooClient:

    def __init__(self):
        """
        Initializes XML-RPC endpoints used for authentication
        and querying Odoo models/data.
        """

        # endpoint used for authentication
        self.common = xmlrpc.client.ServerProxy(
            f"{ODOO_URL}/xmlrpc/2/common"
        )

        # endpoint used for querying models/data
        self.models = xmlrpc.client.ServerProxy(
            f"{ODOO_URL}/xmlrpc/2/object"
        )

        self.uid = None

    def authenticate(self):
        """
        Authenticates against the Odoo sandbox instance using
        credentials loaded from the .env configuration file.
        Stores the authenticated user id for future API calls.
        """

        # sends credentials to Odoo
        # returns a user id if successful
        self.uid = self.common.authenticate(
            ODOO_DB,
            ODOO_USERNAME,
            ODOO_PASSWORD,
            {}
        )

        if self.uid:
            print(f"Successfully authenticated with Odoo. UID: {self.uid}")
            return True

        print("Authentication failed.")
        return False

    def get_recent_confirmed_orders(self):
        """
        Retrieves sales orders that:
        1. are confirmed sales orders
        2. fall within the required 48 hour window
        3. contain a populated customer reference / PO number

        In Odoo:
        - the Order Reference (ex: SO1006) is the internal
          sales order number generated by the ERP system.
        - the Customer Reference / PO Number
          (client_order_ref, ex: PO-88214) is the customer's
          purchase order number used for external/business
          tracking of the transaction.
        """

        # current time minus 48 hours
        cutoff = datetime.now() - timedelta(hours=48)

        # Odoo expects datetime strings in this format
        cutoff_string = cutoff.strftime("%Y-%m-%d %H:%M:%S")

        # domain = filters
        #
        # only return orders that:
        # 1. are confirmed sales orders
        # 2. fall within the required 48 hour window
        # 3. contain a populated customer reference / PO number
        #
        # using date_order because it reflects the quotation/order
        # timestamp shown in the Odoo UI. this is the business-facing
        # order date associated with the sales order workflow.
        domain = [
            ("state", "=", "sale"),
            ("date_order", ">=", cutoff_string),
            ("client_order_ref", "!=", False),
        ]

        # fields = columns/data we want returned
        fields = [
            "name",
            "partner_id",
            "client_order_ref",
            "date_order",
            "create_date",
            "amount_total",
            "order_line",
        ]

        # query the sale.order model
        orders = self.models.execute_kw(
            ODOO_DB,
            self.uid,
            ODOO_PASSWORD,
            "sale.order",
            "search_read",
            [domain],
            {"fields": fields},
        )

        return orders

    def get_order_lines(self, order_line_ids):
        """
        Retrieves sale.order.line records associated with
        a specific sales order.

        Order lines represent the individual parts/components
        contained within a sales order.
        """

        # fields needed from each sale.order.line record
        fields = [
            "product_id",
            "product_uom_qty",
        ]

        # read the order line records associated with a sale.order
        lines = self.models.execute_kw(
            ODOO_DB,
            self.uid,
            ODOO_PASSWORD,
            "sale.order.line",
            "read",
            [order_line_ids],
            {"fields": fields},
        )

        return lines

    def get_part_summary_items(self, order_line_ids):
        """
        Converts order line records into readable
        quantity/product summary strings such as:
        "3x Sensor Mount"
        """

        # convert order line records into readable
        # "3x Product Name" strings
        lines = self.get_order_lines(order_line_ids)

        parts = []

        for line in lines:

            # product_id returns:
            # [product_id, product_name]
            product_name = line["product_id"][1]

            quantity = line["product_uom_qty"]

            parts.append(f"{quantity:g}x {product_name}")

        return parts

    def group_orders_with_parts(self, orders):
        """
        Groups matching orders together and consolidates
        all associated parts/components into a single
        Part Summary output.

        Handles both:
        1. standard Odoo multi-line sales orders
        2. imported demo data where the same order
           may appear multiple times with one part
           per imported row
        """

        # stores grouped order information
        grouped_orders = {}

        for order in orders:

            order_name = order["name"]

            po_number = order["client_order_ref"]

            # group by both order number and PO number
            #
            # this handles two possible Odoo data situations:
            #
            # 1. normal ERP structure:
            #    one sale.order contains multiple sale.order.line
            #    records representing multiple parts/components.
            #
            # 2. imported demo CSV structure:
            #    the same quotation/order reference may appear
            #    multiple times, where each imported row stores
            #    a single quoted part independently.
            #
            # grouping allows both cases to produce one final
            # consolidated Part Summary output.
            group_key = (order_name, po_number)

            if group_key not in grouped_orders:

                grouped_orders[group_key] = {
                    "name": order_name,
                    "customer": order["partner_id"][1],
                    "po_number": po_number,
                    "order_date": order["date_order"],
                    "parts": [],
                }

            # fetch all part summary items associated
            # with the current order/order lines
            part_items = self.get_part_summary_items(
                order["order_line"]
            )

            # append part summaries into one grouped order
            grouped_orders[group_key]["parts"].extend(
                part_items
            )

        return list(grouped_orders.values())
